apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-operator-helm.configmapNameAccess" . }}
  namespace: {{ include "kafka-operator-helm.namespace" . }}
data:
  access-config.properties: |
    file.topic1=test1
  baseurl: {{ .Values.baseurl }}