apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka-operator-helm.rolebindingname" . }}
  namespace: {{ include "kafka-operator-helm.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka-operator-helm.serviceAccountName" . }}
    namespace: {{ include "kafka-operator-helm.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "kafka-operator-helm.rolename" . }}
  apiGroup: rbac.authorization.k8s.io