{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-operator-helm.serviceAccountName" . }}
  namespace: {{ include "kafka-operator-helm.namespace" . }}
{{- end }}



